<script type="text/javascript">
    $(document).ready(function() {
        utils.validateForm("changePasswordForm");
    });
</script>
<?php
$title = 'Change Password';
$this->headTitle($title);
?>
<div class="row-fluid">
    <div class="span16">
        <div class='glass-bg'>
            <header>
                <h2 class="green">Change Password</h2>
                <hr/>
            </header>
            <div class="pad-15">
                <?php echo $this->partial('application/flash-message/processMessage.phtml', array('flashMessages' => $this->flashMessages, 'error'         => $this->error)); ?>
                <?php
                $form  = $this->form;
                $form->setAttribute('action', $this->url('users/change-password'));
                $form->setAttribute('id', 'changePasswordForm');
                $form->prepare();

                echo $this->form()->openTag($form);
                echo "<div class='row-fluid'>";
                foreach ($form as $element) :
                    ?>
                    <div class="control-group <?php if ($element->getName() == 'cpassword' || $element->getName() == 'cpassword' || $element->getName() == 'password') { ?>chnage-pass-row <?php } ?><?php if ($this->formElementErrors($element)) echo "error" ?>">
                        <label class="control-label blue txt-hossbrag"><?php echo $element->getLabel() ?></label>
                        <div class="controls">
                            <?php
                            echo $this->formElement($element);
                            if ($this->formElementErrors($element)):
                                ?>
                                <span class="help-inline"><?php echo $this->formElementErrors($element); ?></span>
                                <?php
                            endif;
                            ?>
                        </div>
                        <?php
//                        if ($element->getName() == "password") {
//                            echo '<div id="complexity" style="width:160px;"></div>';
//                        }
                        ?>
                    </div>
                    <?php
                endforeach;
                ?>

                <span  class = "txt-hossbrag right hoss-cancel-txt pad-left-10 pad-right-25" onclick="redirect('app/home');">Cancel</span>
                <div id="complexity" class="right margin-right-05" style="width:160px;"></div>
            </div>
            <?php
            echo $this->form()->closeTag();
            ?>

            <?php
            /*
              echo $this->status;
              if ($this->status === true) {
              ?>
              <div class="alert alert-success">Password changed successfully.</div>
              <?php
              } else if ($this->status === false) {
              ?>
              <div class="alert alert-error">Unable to update your password. Please try again.</div>
              <?php
              }

              echo $this->form()->openTag($form);
              $form_array = array();
              foreach ($form as $element) {
              $form_array[$element->getName()] = $element;
              }
              ?>
              <div class="row-fluid">
              <?php
              $element = $form_array['identity'];
              $element->setValue($this->zfcUserIdentity()->getEmail());
              ?>
              <div class="control-group
              <?php
              if ($this->formElementErrors($element)) {
              echo "error";
              }
              ?>">
              <label class="control-label blue txt-hossbrag"><?php echo $element->getLabel() ?></label>
              <div class="controls">
              <?php
              echo $this->formElement($element);
              ?>
              </div>
              </div>
              </div>


              <div class="row-fluid">
              <?php
              $element = $form_array['credential'];
              $element->setAttribute('class', 'input-medium');
              $element->setAttribute('style', 'width: 92%');
              ?>
              <div class="control-group span8
              <?php
              if ($this->formElementErrors($element)) {
              echo "error";
              }
              ?>">
              <label class="control-label blue txt-hossbrag"><?php echo $element->getLabel() ?></label>
              <div class="controls">
              <?php
              echo $this->formElement($element);
              ?>
              </div>
              </div>
              <?php
              $element = $form_array['newCredential'];
              $element->setAttribute('class', 'input-medium');
              $element->setAttribute('style', 'width: 92%');
              ?>
              <div class="control-group span8
              <?php
              if ($this->formElementErrors($element)) {
              echo "error";
              }
              ?>">
              <label class="control-label blue txt-hossbrag"><?php echo $element->getLabel() ?></label>
              <div class="controls">
              <?php
              echo $this->formElement($element);
              ?>
              </div>
              </div>
              <?php
              $element = $form_array['newCredentialVerify'];
              $element->setAttribute('class', 'input-medium');
              $element->setAttribute('style', 'width: 92%');
              $element->setLabel("Re-type New Password");
              ?>
              <div class="control-group span8
              <?php
              if ($this->formElementErrors($element)) {
              echo "error";
              }
              ?>">
              <label class="control-label blue txt-hossbrag"><?php echo $element->getLabel() ?></label>
              <div class="controls">
              <?php
              echo $this->formElement($element);
              ?>
              </div>
              </div>
              </div>

              <div class="row-fluid pad-top-10">
              <div class="span12">
              <div class="control-group ">
              <div class="controls-left">
              <input type="checkbox" name="send_me_email" value="" class="left">
              </div>
              <div class="controls-left">
              <label><span class="txt-hossbrag-gotham pad-left-05" style="font-size: 11px;">Send me an e-mail containing the new password.</span></label>
              </div>
              </div>
              </div>
              <div class="span12" style="text-align: right;">
              <span  class = "txt-hossbrag  hoss-cancel-txt pad-right-25" onclick="redirect('app/home');">Cancel</span>
              <!--<a class="btn btn-primary  btn-same-width" href="<?php echo $this->url('web_app/profile/public', array('fullName' => $this->zfcUserIdentity()->fullName(), 'id'       => $this->zfcUserIdentity()->getId())); ?>">Cancel</a>-->
              <button type="submit" value="Change" class="btn btn-success required  btn-same-width">Change</button>
              </div>

              </div>


              <?php
              echo $this->form()->closeTag();
              ?>
             */
            ?>
        </div>


    </div>
</div>
<div class="right-container span8">
    <?php
    echo $this->partial('web-app/profile/boxes/right-menu-nav.phtml');
    echo $this->RecommandedContact_widget();
    echo $this->RecommandedJob_widget();
    echo $this->statistics_widget();
    ?>

</div>
</div>



