<?php
$title = 'Confirm E-mail';
$this->headTitle($title);
?>
<div class="row-fluid">
    <div class="span16 offset4 text-center pad-bottom-10"><img src="<?php echo $this->basePath('/images/reg_step3_process.png') ?>" alt="Hossbrag Registration Step2 processbar"/></div>
</div>
<div class="row-fluid">
    <div class="span16 offset4">
        <div id="newToHossbragRegForm" class="new-to-hossbrag outer-frame-bottom">
            <div class="outer-frame">
                <div class="inner-frame" style="background-color: #fafafa;padding-bottom: 10px;">
                    <h1><?php echo $this->escapeHtml($title); ?></h1>

                    <div class="pad-05 marginbottom">
                        <?php echo $this->partial('web-app/flash-message/processMessage.phtml', array('flashMessages' => $this->flashMessages, 'error'         => $this->error)); ?>
                        <?php
                        $form  = $this->form;
                        $form->setAttribute('action', $this->url('users/confirmEmail', array('id' => $this->id,)));
                        $form->prepare();

                        echo $this->form()->openTag($form);
                        echo $this->formHidden($form->get('id'));
                        foreach ($form as $element) :
                            ?>
                            <div class="control-group <?php if ($this->formElementErrors($element)) echo "error" ?>">
    <!--                                <label class="control-label"><?php // echo $element->getLabel()   ?></label>-->
                                <div class="controls">
                                    <?php
                                    echo $this->formElement($element);
                                    if ($this->formElementErrors($element)):
                                        ?>
                                        <span class="help-inline"><?php echo $this->formElementErrors($element); ?></span>
                                        <?php
                                    endif;
                                    ?>
                                </div>
                            </div>
                            <br class="clearboth">
                            <?php
                        endforeach;
                        echo $this->form()->closeTag();
                        ?>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>