<?php
$title = 'Forget your password?';
$this->headTitle($title);
?>
<div class="row-fluid">
    <div class="span16 offset4">
        <div class="new-to-hossbrag outer-frame-bottom" id="newToHossbragRegForm">
            <div class="outer-frame">
                <div class="inner-frame">
                    <h1 class="blue">Forgot Your Password?</h1>
                    <br>
                    <?php echo $this->partial('web-app/flash-message/processMessage.phtml', array('flashMessages' => $this->flashMessages, 'error'         => $this->error)); ?>
                    <br>
                    <?php
                    $form  = $this->form;
                    $form->setAttribute('action', $this->url('users/forget-password'));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $name  = $form->get('username');
                    $email = $form->get('email');
                    ?>
                    <div class="control-group" style="margin-bottom: 0px;">
                        <?php echo $this->formInput($name); ?>
                        <button style="width: 100px; margin-left: 20px;" class="btn btn-primary " type="submit">Submit</button>
                    </div>
                    <div class="or_divider pad-top-10 pad-bottom-10"><strong>or</strong></div>
                    <div class="control-group ">
                        <?php echo $this->formInput($email); ?>
                        <button style="width: 100px; margin-left: 20px;" class="btn btn-primary " type="submit">Submit</button>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>

                    </form>
                    <div style="padding-bottom: 30px;" class="txt-hossbrag-gotham">
                        <strong><span class="black">Need Help? Contact us:</span> <a href="mailto:team@hossbrag.com">team@hossbrag.com</a></strong>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



