<?php
$title      = 'User Log in';
$this->headTitle($title);
?>
<div class="row-fluid">
    <div class="span12">
        <div id="newToHossbragRegForm" class="new-to-hossbrag outer-frame-bottom">
            <div class="outer-frame">
                <div class="inner-frame">

                    <?php echo $this->partial('application/flash-message/processMessage.phtml', array('flashMessages' => $this->flashMessages, 'error'         => $this->error)); ?>
                    <div class="row-fluid">
                        <div class="span6">
                            <h1 class="blue"><?php echo $this->escapeHtml($title); ?></h1>
                            <div class='pad-right-20'>
                                <?php
                                $form       = $this->form;
                                $form->setAttribute('action', $this->url('users/authenticate'));
                                $form->prepare();
                                echo $this->form()->openTag($form);
                                ?>
                                <?php
                                $name       = $form->get('username');
                                ?>
                                <div class="control-group text-left <?php if ($this->formElementErrors($form->get('username'))) echo "error" ?>">
                                    <label><span class="txt-hossbrag">User Name</span>
                                        <?php
                                        echo $this->formInput($name);
                                        ?>
                                    </label>
                                </div>
                                <?php
                                $password   = $form->get('password');
                                ?>
                                <div class="control-group text-left<?php if ($this->formElementErrors($form->get('password'))) echo "error" ?>">
                                    <label><span class="txt-hossbrag">Password</span>
                                        <?php
                                        echo $this->formInput($password);
                                        ?>
                                    </label>
                                </div>
                                <div class="pad-bottom-10 text-left">
                                    <label>
                                        <?php
                                        $rememberme = $form->get('rememberme');
                                        $rememberme->setValue(1);
                                        echo $this->formInput($rememberme);
                                        ?><span class="txt-hossbrag-gotham"> keep me logged in</span>
                                    </label>
                                </div>
                                <div style="text-align: left;" class="pad-bottom-10">
                                    <?php
                                    echo $this->formElement($form->get('submit'));
                                    ?>
                                    or <a href="<?php echo $this->url('users/forget-password'); ?>">forgot your password?</a>
                                </div>
                                <?php
                                /*
                                  foreach ($form as $element) :
                                  ?>
                                  <div class="control-group <?php if ($this->formElementErrors($element)) echo "error" ?>">
                                  <label class="control-label" style="text-align: left;"><?php echo $element->getLabel() ?></label>
                                  <div style="text-align: left;">
                                  <?php
                                  echo $this->formElement($element);
                                  if ($this->formElementErrors($element)):
                                  ?>
                                  <span class="help-inline"><?php echo $this->formElementErrors($element); ?></span>
                                  <?php
                                  endif;
                                  ?>
                                  </div>
                                  </div>
                                  <?php
                                  endforeach;
                                 *
                                 */
                                echo $this->form()->closeTag();
                                ?>
                            </div>

                        </div>
                        <div class="span6" style="border-left: 1px solid #ccc;">
                            <h2 class="blue">Not a Member Yet?</h2>
                            <h6 class="black">Sign Up Now &ndash; It´s Free!</h6>
                            <br>
                            <div>
                                <a class="btn btn-large btn-success  join-now" href="<?php echo $this->url('users/registration'); ?>">Join Now</a>
                            </div>
                            <div class='pad-right-10'>
                                <div class="black pad-10">
                                    <strong>Or, save time and sign up <br> with Facebook</strong>
                                </div>
                                <div style="text-align: center;">
                                    <a href="<?php // echo $this->url('scn-social-auth-user/login/provider', array('provider' => 'facebook'))            ?>"><img src="<?php echo $this->basePath('/bootstrap/images/fb_signup.png') ?>" alt="Facebook Signup"/></a>
<!--                                    <a href="#"><img src="<?php echo $this->basePath('/bootstrap/images/twitter_signup.png') ?>" alt="Twitter Signup"/></a>-->
                                </div>
                            </div>

                        </div>
                    </div>


                    <div class="pad-bottom-10"></div>
                </div>
            </div>
        </div>

    </div>
</div>



